name: CI

on: [push]

jobs:
  pre-pull-request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.15.1
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.1

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
