name: Pre PR

on: pull_request

jobs:
  pre-pull-request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.15.1
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.1

      - name: Install dependencies
        run: npm ci

      - name: Check linting
        run: npm run check-linting

      - name: Run tests
        run: npm test
