name: Pre PR

on: [push]

jobs:
  pre-pull-request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.15.1
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.1

      - name: Install dependencies
        run: npm ci

      - name: Tests
        uses: artiomtr/jest-coverage-report-action@v1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #   threshold: 80 # optional parameter
      # - name: Run tests
      #   run: npm run test
