name: Publish Docker image

# Run action when code pushed to master
on:
  push:
    branches:
      - 'master'

jobs:
  # https://github.com/marketplace/actions/build-and-push-docker-images
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # https://github.com/docker/metadata-action - generate Docker meta
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/random-frog-api
          flavor: |
            latest=true
          tags: |
            type=sha,prefix={{branch}}-

      # https://github.com/docker/setup-qemu-action - emulator and virtualizer that can perform hardware virtualization
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # https://github.com/docker/setup-buildx-action - CLI plugin that extends the docker command with the full support of the features provided by Moby BuildKit builder toolkit
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://github.com/docker/build-push-action - GitHub Action to build and push Docker images with Buildx
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
